# Generated by Django 5.0.3 on 2024-04-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CID', models.IntegerField(primary_key=True, serialize=False)),
                ('Cname', models.CharField(max_length=100)),
                ('Fees', models.IntegerField()),
                ('Tname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('SID', models.IntegerField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=100, unique=True)),
                ('Age', models.IntegerField()),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=100)),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
    ]
